//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainerGUIForms.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AISTask", Namespace="http://schemas.datacontract.org/2004/07/AISdb")]
    [System.SerializableAttribute()]
    public partial class AISTask : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float current_errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fpathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TrainerGUIForms.ServiceReference1.TaskType ttypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string author {
            get {
                return this.authorField;
            }
            set {
                if ((object.ReferenceEquals(this.authorField, value) != true)) {
                    this.authorField = value;
                    this.RaisePropertyChanged("author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float current_error {
            get {
                return this.current_errorField;
            }
            set {
                if ((this.current_errorField.Equals(value) != true)) {
                    this.current_errorField = value;
                    this.RaisePropertyChanged("current_error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fpath {
            get {
                return this.fpathField;
            }
            set {
                if ((object.ReferenceEquals(this.fpathField, value) != true)) {
                    this.fpathField = value;
                    this.RaisePropertyChanged("fpath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrainerGUIForms.ServiceReference1.TaskType ttype {
            get {
                return this.ttypeField;
            }
            set {
                if ((this.ttypeField.Equals(value) != true)) {
                    this.ttypeField = value;
                    this.RaisePropertyChanged("ttype");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskType", Namespace="http://schemas.datacontract.org/2004/07/AISdb")]
    public enum TaskType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneticAlgorithm = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArtificialNeuralNetwork = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTasks", ReplyAction="http://tempuri.org/IService1/getTasksResponse")]
        TrainerGUIForms.ServiceReference1.AISTask[] getTasks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getNeuralNetwork", ReplyAction="http://tempuri.org/IService1/getNeuralNetworkResponse")]
        ANeuralNetwork.ANetwork getNeuralNetwork(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setNetworkResults", ReplyAction="http://tempuri.org/IService1/setNetworkResultsResponse")]
        void setNetworkResults(int id, ANeuralNetwork.ANetwork net, float newError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getError", ReplyAction="http://tempuri.org/IService1/getErrorResponse")]
        float getError(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStudyData", ReplyAction="http://tempuri.org/IService1/getStudyDataResponse")]
        ANeuralNetwork.StudyData[] getStudyData(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addStudyData", ReplyAction="http://tempuri.org/IService1/addStudyDataResponse")]
        void addStudyData(int id, ANeuralNetwork.StudyData[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addTask", ReplyAction="http://tempuri.org/IService1/addTaskResponse")]
        void addTask(TrainerGUIForms.ServiceReference1.AISTask tt, string[] parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateTask", ReplyAction="http://tempuri.org/IService1/updateTaskResponse")]
        void updateTask(TrainerGUIForms.ServiceReference1.AISTask tt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteTask", ReplyAction="http://tempuri.org/IService1/deleteTaskResponse")]
        void deleteTask(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAssembly", ReplyAction="http://tempuri.org/IService1/GetAssemblyResponse")]
        byte[] GetAssembly(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAvailableGALibs", ReplyAction="http://tempuri.org/IService1/GetAvailableGALibsResponse")]
        string[] GetAvailableGALibs();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TrainerGUIForms.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TrainerGUIForms.ServiceReference1.IService1>, TrainerGUIForms.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TrainerGUIForms.ServiceReference1.AISTask[] getTasks() {
            return base.Channel.getTasks();
        }
        
        public ANeuralNetwork.ANetwork getNeuralNetwork(int id) {
            return base.Channel.getNeuralNetwork(id);
        }
        
        public void setNetworkResults(int id, ANeuralNetwork.ANetwork net, float newError) {
            base.Channel.setNetworkResults(id, net, newError);
        }
        
        public float getError(int id) {
            return base.Channel.getError(id);
        }
        
        public ANeuralNetwork.StudyData[] getStudyData(int id) {
            return base.Channel.getStudyData(id);
        }
        
        public void addStudyData(int id, ANeuralNetwork.StudyData[] data) {
            base.Channel.addStudyData(id, data);
        }
        
        public void addTask(TrainerGUIForms.ServiceReference1.AISTask tt, string[] parameters) {
            base.Channel.addTask(tt, parameters);
        }
        
        public void updateTask(TrainerGUIForms.ServiceReference1.AISTask tt) {
            base.Channel.updateTask(tt);
        }
        
        public void deleteTask(int id) {
            base.Channel.deleteTask(id);
        }
        
        public byte[] GetAssembly(string name) {
            return base.Channel.GetAssembly(name);
        }
        
        public string[] GetAvailableGALibs() {
            return base.Channel.GetAvailableGALibs();
        }
    }
}
